### ISSUE TITLE
Vega-specification in markdown fenced code blocks

### ISSUE THREAD

**Issue by nikolatulechki** [data-for-good-bg/data-for-good-bg.github.io#13]
# Context 
We currently support vega and vega-lite data visualizations 
The json specifications litely wrapped in html can directly be inserted in the markdown source files on the website and rendered

The workflow that we will most commonly use is to draw such graphics in python notebooks using altair and then copy/paste the spec in the body of the markdown blog post. See [this](https://colab.research.google.com/drive/1S00WQlsn4vGiEkuHLkL2MeAQeFCVkeTb) collab notebook for an example of many such graphics

#Issue 
The current solution, while perfectly functional has the following issue:

When more than one visualization is inserted, such as in  [2022-12-23-stem-maturi-2021.md](https://github.com/data-for-good-bg/data-for-good-bg.github.io/blob/main/bg/_posts/2022-12-23-stem-maturi-2021.md), the writer has to handle himself the naming of the js variables as well as the id (and existance) of the div where the result is renderd (e.g vegaEmbed('#vis2', vlSpec2)) for the second visualization.
Furthermore the code is displayed hidously  when vued as github markdown.

# Improvement 
This can be improved if instead if wrapping in `html` elements is done automatically and not by the user.
This can be achieved by having the user to just paste the `vega-spec` in a fenced code block 
and implementing some logic that looks for such code blocks and wraps them them with the right `html` elements. 

This will greatly improve the usability of the workflow, 
will solve the rendering issue 
and will allow much easier writing of blogs as fenced code blocks can be collapsed in most modern IDEs.

In order to keep the syntax high lighting working, the codeblocks should remain json 
 we propose to indicate that it is a special code block by adding a second word after the format, such as 

```
```json vega-lite 
{
    $schema: 'https://vega.github.io/schema/vega-lite/v5.json',
    description: 'рисков вот - разлика в мандати по партия',
    data: {

}
```
# Additional requirements
- it must be possible to insert many vega-lite specifications and each one should function autonomously 
- on the rendered pages the visualizations should appear in the text where the code block is situated 
- vanilla `json` fenced code blocks should not be afected and should appear in the rendered page

**Comment by dbalinov** [comment]
@nikolatulechki This task is resolved with the new Hugo version of the website.

You can see an example here:
https://github.com/data-for-good-bg/data-for-good-bg.github.io/blob/main/content/posts/2023-08-12-matura-stem-over-time.md

I will close it.
